name: Download Makkal Kural E-Paper

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 4 * * *'  # every day at 4 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests PyPDF2

    - name: Run the script
      run: python run.py

    - name: Commit PDF file
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add *.pdf
        git commit -m "Add today's Makkal Kural PDF" || echo "No changes to commit"
        git push
