name: Download Makkal Kural

on:
  schedule:
    - cron: '30 2 * * *'  # 8 AM IST daily (1:00 AM UTC)
  workflow_dispatch:     # Allows manual run

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Download Makkal Kural PDF
      run: |
        python <<EOF
        import requests
        from datetime import datetime

        today = datetime.now().strftime("%d-%m-%Y")
        url = f"https://makkalkural.tv/newspaper/{today}.pdf"
        response = requests.get(url)
        if response.status_code == 200:
            filename = f"MakkalKural_{today}.pdf"
            with open(filename, "wb") as f:
                f.write(response.content)
        else:
            raise Exception(f"Failed to download: {response.status_code}")
        EOF

    - name: Commit and push PDF
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add *.pdf
        git commit -m "Add today's Makkal Kural PDF" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/8088yyy/news.git HEAD:main
