name: Download and Upload PDF

on:
  workflow_dispatch:  # allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python run.py

    - name: Show output files
      run: ls -lh *.pdf || echo "No PDF generated"

    - name: Commit PDF to repository
      if: success()
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        PDF_NAME=$(ls MakkalKural_*.pdf | head -n 1 || echo "")
        if [ -z "$PDF_NAME" ]; then
          echo "❌ No PDF generated. Skipping commit."
          exit 1
        fi
        git add "$PDF_NAME"
        git commit -m "📰 Add daily PDF: $PDF_NAME"
        git push
